### ISSUE TITLE
Suggestion: Warning about PHP 8

### ISSUE THREAD

**Issue by PlayBoxTech** [jgonyea/grav-plugin-get-id3#6]
As the GetID3 doesn't work under PHP 8, there should be a warning that pops up if user has php 8 active and tries to install / activate the Get ID3 plugin.

**Comment by jgonyea** [comment]
I agree, this is a good item to add in.

**Comment by jgonyea** [comment]
Should now be fixed in 1.0.4. For now, remove the entire plugin folder and reinstall v1.0.4 to retrieve the new library folder
